### ISSUE TITLE
Download missing dependencies from package management

### ISSUE THREAD

**Issue by kine** [kine/navertical#1]
Functions to use nuget to download the app files is prepared, but there is no fallback to use this when the dependency is not part of the source code in the Compile-ALAppTree and Publish-ALAppTree.

When the NVRAppDevOps will incorporate this, this issue will be solved.

**Comment by epernst** [comment]
If you mean making it possible to download and install dependent apps from my app.json that are not in the dependency folder, then I am looking very much forward to it.

**Comment by kine** [comment]
Prepared for Compile-ALProjectTree cmdlet. 
Next step will be the Install-ALAppTree cmdlet.

**Comment by kine** [comment]
Ok, done.
commit 241afa3e98b30848b036c234d7a4ed855bb5dd7a
commit 0dcc1dcac7d1d19e77a02d6360db8cb3bc027123

**Comment by epernst** [comment]
How is it going to work? Will I be able to pull the files from my artifacts?
