### ISSUE TITLE
Cannot read settings

### ISSUE THREAD

**Issue by epernst** [kine/navertical#10]
I think there is an issue with repository names with spaces. When I use "Show Configuration", then the output I'm getting is:
PS C:\Users\epernst\Git\EPE\BC Extension Template\MainApp> Read-ALConfiguration -Path c:\Users\epernst\Git\EPE\BC Extension Template\MainApp\..

ContainerName      :
ImageName          :
LicenseFile        :
VsixPath           :
PlatformVersion    :
AppVersion         :
TestAppVersion     :
AppName            :
TestAppName        :
AppFile            :
TestAppFile        :
Publisher          :
TestPublisher      :
RepoPath           :
AppPath            :
TestAppPath        :
Build              : Extension
Password           : Template\MainApp\..
Username           : epernst
Auth               : Windows
ClientPath         :
AppDownloadScript  :
RAM                :
DockerHost         :
DockerHostCred     :
DockerHostSSL      : False
DockerHostPathMap  :
optionalParameters :

The consequence is the Build Environment doesn't work. 

Removing the spaces in the folder works, but since Azure DevOps accepts spaces, then it would be great if navertical also did.

**Comment by kine** [comment]
You can try the latest version. Should be fixed.

**Comment by epernst** [comment]
Thanks Kamil, great work. Will test it out later this week, unless you made a Pester test script for it. 👍

**Comment by kine** [comment]
Than I will need to learn how to use Pester and how to test something togetherwith the powershell console... :-)

**Comment by epernst** [comment]
I can give you a quick intro to Pester next week, if we can find 15 minutes. :)
