### ISSUE TITLE
Process Isolation

### ISSUE THREAD

**Issue by KristofKlein** [kine/navertical#11]
Since MS has introduced process isolation possibilities with ltsc2019 and docker I ran into the issue that I do not want it to be like that :D Based on the IT infrastructure I'm in I'm not able to use process isolation (which became default in Freddys tools) but classic hyperv instead.  Is there a way how I can influence the container creation NOT to use process isolation? I know navcontainerhelper supports it with parameter isolation set to hyperv.
--
Update: I changed a bit your powershell scripts to take in one more parameter from the settings.json. like this i can now control the isolation handling.

**Comment by kine** [comment]
This is more connected with the https://github.com/kine/NVRAppDevOps than with the NaverticAl extension, because there is no support in this module for it now. I am just now working on some changes in the configuration used in this module and it will have impact even to the NaverticAl. I will try to incorporate this switch there too.

**Comment by KristofKlein** [comment]
Yes. You are right. I noticed it to late 😀 actually I did what you described just myself and added another parameter such that I can control it with the settings.json. Thanks for the reply!

Best regards / Mit freundlichen Grüssen / Med venlig hilsen

Kristof Klein
Software Architect

[X]





Office:

+45 73425050<tel:+45%2073425050>

  Nørre Havnegade 43<x-apple-data-detectors://0/1>

Direct:

+45 73425053<tel:+45%2073425053>

  6400 Sønderborg

Mobile:

+45 20536561<tel:+45%2020536561>

  Denmark

kristof.klein@hsntech.com<mailto:kristof.klein@hsntech.com>

  www.hsntech.com<http://www.hsntech.com/>


Am 25.02.2019 um 16:47 schrieb Kamil Sacek <notifications@github.com<mailto:notifications@github.com>>:


This is more connected with the https://github.com/kine/NVRAppDevOps<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kine_NVRAppDevOps&d=DwMFaQ&c=50QIlj_rdvCHMJgBy2QFEw&r=Ev7JeGoDYFGHHMEwNn3MRczviMFmE_N2X-1F90cX1tM&m=MvcPn-vcwihZIsvOiAfXO5yOeVxvnbWmOR35iCeiazA&s=jEbRmm8hug-rvvnNy181zFnmOOjljJhO_eAEe19vI4A&e=> than with the NaverticAl extension, because there is no support in this module for it now. I am just now working on some changes in the configuration used in this module and it will have impact even to the NaverticAl. I will try to incorporate this switch there too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kine_navertical_issues_11-23issuecomment-2D467062157&d=DwMFaQ&c=50QIlj_rdvCHMJgBy2QFEw&r=Ev7JeGoDYFGHHMEwNn3MRczviMFmE_N2X-1F90cX1tM&m=MvcPn-vcwihZIsvOiAfXO5yOeVxvnbWmOR35iCeiazA&s=_VunIfVUnvCwhokkusa4eyFuK_sKQ-Evmu-FriCW5VY&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWaYLX9eZIbsvlyOJzItHfy6-2D48H-5Fay1ks5vRAWdgaJpZM4a9jSK&d=DwMFaQ&c=50QIlj_rdvCHMJgBy2QFEw&r=Ev7JeGoDYFGHHMEwNn3MRczviMFmE_N2X-1F90cX1tM&m=MvcPn-vcwihZIsvOiAfXO5yOeVxvnbWmOR35iCeiazA&s=8EfRMds58SuDhcb6w47C90qO0kB37K08bvYP7CS3jgU&e=>.

Notice:  This e-mail and any attachments are confidential and may contain legally privileged information and/or copyright material of Hansen Technologies Limited or third parties.  Copying, distributing, disclosing, commercialising or otherwise acting in reliance on this e-mail and any attachments is strictly prohibited unless you are the addressee of this e-mail and have written permission to do so.  If you have received this e-mail in error please delete this e-mail (including any copies and attachments) and contact Hansen Technologies Limited by return e-mail or by telephone on + 61 3 9840 3000.  Any views expressed in this e-mail are those of the individual sender and may not necessarily reflect the views of or be a commitment by the organisation, except where the individual sender has the authority and expressly states them to be so.
