### ISSUE TITLE
Workspace Name more generic

### ISSUE THREAD

**Issue by duichwer** [kine/navertical#17]
I had the challenge that this extensions didn't work at first with my own template repository since I didn't name my workspace file as it was expected:
https://github.com/kine/navertical/blob/02eaeee949addd0b920d27c868a63828972fc481/src/newapp.ts#L174

Maybe as an enhancement this could be made more generic by looking for the a `*.workspace` file inside the newPath?

**Comment by kine** [comment]
Fixed in v 0.5.2 (d229049baecfc73f1196ed4f58c590c256a8d12a)
