### ISSUE TITLE
Use id instead of appid for runtime >=4.1

### ISSUE THREAD

**Issue by pri-kise** [kine/navertical#18]
Update the `id` instead of `appId` dependend on the specified runtime inside the app.json.
https://github.com/kine/navertical/blob/36973f0c8a4d889614a172308181b6cc66aa5876/src/newapp.ts#L188

> 'dependencies.appId' is being deprecated in the versions: '4.1' or greater. The appId dependency value is being deprecated. Use id instead. This warning will become an error in a future release.

**Comment by kine** [comment]
Published in v0.5.3
