### ISSUE TITLE
Remote DockerHost support?

### ISSUE THREAD

**Issue by waldo1001** [kine/navertical#2]
I never install docker on Win10.  And it seems this system assumes that I have it running on the host where I'm developing, right?

Any chance you'll support "remote docker host" any time soon?

**Comment by kine** [comment]
My brain is going into loop when I am thinking about how to run something remote to do something remote. I was never using such a configuration. I know that it should be simple. May be just opening remote shell before I run all the scripts will be enough? Seems easily doable if it will work...

**Comment by kine** [comment]
Hmmm, it will not be so easy... right now I am doing many things outside the container (compilation etc.), thus it is not just about running the scripts on the host, but having there the source, app files etc. Thus more things will be needed. First I will need to change it to do everything inside the container. And e.g. running the tests right now I am not able to move, because I am running the client in console mode on the host...

**Comment by kine** [comment]
@waldo1001 may be you have tip, how to "push" the code inside the container which is hosted on something else than my localhost. How are you doing it? I remember some discussion about this subject, and if I remember correctly, you are sharing some folder or something. I need to have clear and easy setup for this, which will be used by everyone. Is there some "standardized" way you see/teach/use?

**Comment by waldo1001** [comment]
It is a challenge, indeed :-).  What I did, is I created a "remote docker host helper" module in PowerShell:
http://www.waldo.be/2018/02/15/crs-remotenavdockerhosthelper-updated/

It is actually "just" a wrapper to run scripts remotely, which actually will always "invoke-command" to a certain machine, and execute a scriptblock.  one example here:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/CRS.RemoteNAVDockerHostHelper/ContainerMgt/New-RDHNAVContainer.ps1

here is the module:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/tree/master/PSModules/CRS.RemoteNAVDockerHostHelper

When looking at a VSCode Extension, I'd think of creating settings like:
- navertical.dockerhost
- navertical.dockerhostusessl
- navertical.credentials (allthough, I don't know how to save this securely)

if set up - just remotely execute them... 

Something like that?

**Comment by waldo1001** [comment]
About moving files, I created these functions:
Copy-FileFromDockerHost:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/CRS.RemoteNAVDockerHostHelper/Misc/Copy-FileFromDockerHost.ps1
Copy-FileToDockerHost:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/CRS.RemoteNAVDockerHostHelper/Misc/Copy-FileToDockerHost.ps1

**Comment by kine** [comment]
Do you think that having source codes placed on shared folder on the host is possible solution? I think that VSCode should not have a problem with working on network folder/mapped disk. Than I can just map the folder on the host to the container and only make mapping between local path and real host path. What do you think, @waldo1001 ?

**Comment by waldo1001** [comment]
For sources, that should be possible, yes.  It's merely an issue for remoting into the container.

**Comment by kine** [comment]
With support for process isolation on Windows 10 for Docker on new builds I will drop this and will not continue with the support for remote host for now.

**Comment by waldo1001** [comment]
Aight - setting up docker on win10 now ;-)
