### ISSUE TITLE
Error when running git init: spawnSync git.exe ENOENT. 

### ISSUE THREAD

**Issue by duichwer** [kine/navertical#20]
On some computers I receive the following error:

> Error when running git init: spawnSync git.exe ENOENT. 
May be git was not found? (if  spawn git ENOENT)

I don't know what I'm doing wrong or what is configured wrong since the normal git extension does work very well on my computers...

**Comment by duichwer** [comment]
The strange thing is, that I receive this error only the on the first try. 
If I restart the process with `NaverticAL : Go!` everything works fine.

**Comment by kine** [comment]
Yup, have same issues, mostly when I am using VSCode for some time, it us ok. If I run VSCode and run the Go! it fails first and second try works. I was trying to find the reason but failed. I am learning the TypeScript and all around too... totally newbie in this...

**Comment by duichwer** [comment]
I like the simpleness of the current approach, but maybe this would need a better resolving of the executable path like here:
https://github.com/mhutchie/vscode-git-graph/blob/1c4cd1d2e4c6cb0a4ef93e93467b2371b8e763b3/src/utils.ts#L431

**Comment by kine** [comment]
I think I will need to ask someone more experienced in JavaScript for that, because I think the problem is somewhere in the async things around (it is why sometime it works and mostly after fresh start not...). Seems like something in node.js is not inited or something in time of the call...

**Comment by kine** [comment]
@duichwer  try the 0.5.6 version if it is solved, please.

**Comment by duichwer** [comment]
I created many new projects and never received this error anymore. Seems resolved
