### ISSUE TITLE
Create environment error

### ISSUE THREAD

**Issue by peterz84** [kine/navertical#5]
I'm trying to execute the Create Environment command. It asks me for my credentials and then gives me the following error:

```
PS C:\Dev\Course 365\Scripts> Read-ALConfiguration -Path c:\Dev\Course 365\Scripts\.. | Init-ALEnvironment
Build is 365\Scripts\..
New-NavContainer : Cannot bind argument to parameter 'containerName' because it is an empty string.
At C:\Users\<<<myusername>>>\OneDrive\Documenten\WindowsPowerShell\Modules\NVRAppDevOps\0.9.46\Init-ALEnvironment.ps1:78 char:40
+                         -containerName $ContainerName `
+                                        ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-NavContainer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-NavContainer
```

Do you have any idea what to do? It looks like the Settings.ps1 isn't read properly?

**Comment by kine** [comment]
I cannot tell when I do not see your settings.ps1, but it seems that the variable $ContainerName is not set to the container name you want to use. Even it seems that there is variable $Build set to value 365\Scripts\.., which should be "true" when running from Agent.

**Comment by peterz84** [comment]
I think I found the error: My container name was Course 365, but the script does not support spaces. If I use Course365 it runs fine.

**Comment by epernst** [comment]
It is not a limitation in the script, it's Docker who doesn't allow it.
