### ISSUE TITLE
Question: What do you mean by Add dependency Apps into Dependencies folder as GIT Submodules (preffered) or directly

### ISSUE THREAD

**Issue by peterz84** [kine/navertical#6]
Do you have an example?

**Comment by kine** [comment]
Example of what? How to add git repo as submodule of another git repo? See https://git-scm.com/docs/git-submodule

There is no standard way how to do that in VSCode directly (only using console in VSCode). If you are using another GIT GUI, there should be functionality for it. E.g. for GIT Extensions see https://git-extensions-documentation.readthedocs.io/en/latest/submodules.html

You need first to understand how the submodules in GIT are working. But I think it is worth of learning it. You can google the explanation and examples.

VSCode is supporting submodules, it is able to work with them correctly, but there is no default way to add them yet.

**Comment by peterz84** [comment]
Thanks, wasn't familiar with submodules.
