### ISSUE TITLE
Suggestion: Run Tests from VSCode

### ISSUE THREAD

**Issue by epernst** [kine/navertical#7]
May I suggest an enhancement?
We already have the setup to allow to run the test suite for the extension used by the Yml defintion. 
As a developer I would like to be able to run the tests in my extension, without having open the client and return the result visible in VSCode.

That would make it much easier to do TDD. 
The Publish/Unpublish Tree is already a time savior in that regard.

**Comment by kine** [comment]
I think this is doable, question is, how to display the test results in some graphical way. Based on the way the result format could be prepared. Rest is just about running Test-ALApp cmdlet with propper parameters (right now output is TRX file).

**Comment by epernst** [comment]
Don't really care how it looks, if there are no errors, then it should just display "Test Successful" - or list any failures it the fastest way possible. The faster it can do it, the better TDD.
Leave it to the test results file in DevOps to make something beautiful! :)

**Comment by kine** [comment]
Done, using the navcontainerhelper cmdlet to run the tests inside the container. Use the latest version of the modules and the extension. Look for "navertical: Run Tests". It is running default test suite...
